var GAME_LEVELS = [
  ["                                                             v                   ",
   "                                                                                ",
   "                                                                                ",
   "              v                                   v                               ",
   "                                                                                 ",
   "                                         v                                        ",
   "                                                                                 ",
   "                                                       xxx                    ",
   "                                              xxx                               ",
   "                              m       xxx                                       ",
   "                             xxxx                            o                   ",
   "                        o                                    xx                    ",
   "                     xxxx                                    xx                     ",
   "                                                             xx   xx                 ",
   "            xxxx                                             xx       xx              ",
   "      @                                                      xx                   ",
   "   xxxxxx                                                    xx          xx            ",
   "  xx    xx                                                   xx                     ",
   "  x      x                                                   xx             xx           ",
   "  x      x                                                   xx                   ",
   "  x      x                                                   xx                    ",
   "  x      x                                                   xx                    ",
   "!!x      x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!x    o      ",
   "xxx      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    "],
  ["                                                                                                                 ",
   "                                                                                                                 ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                                ",
   "                                                                                                                ",
   "     @                                                                                                           ",
   "    xxx                                                                                                            ",
   "                                                                                                                 ",
   "                                                                                                                ",
   "                                                                                                                 ",
   "                                                                                                                ",
   "                                                                                                                 ",
   "         xxx                                                                                                       ",
   "                                                                                                                 ",
   "                                  v                                                                               ",
   "                                                                                                                 ",
   "                                                                                                                 ",
   "               o                                                                                                 ",
   "              xxx                                                                                                   ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                  x!!!!x  xxxx   xxx                                    xxx                          ",
   "                  xxxxxx         xxx                                  o xxx                          ",
   "                                 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                                                ",
   "                                                                                                                 ",
   "                                                                                                                 ",
   "                                                                                                                 ",
   "                                                                                                                 ",
   "                                                                                                                 "],
  ["                                                                                                                 ",
   "                                                                                                                 ",
   "                                                                                                               ",
   "                                                                                                               ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                ",
   "                                                                                                                 ",
   "                                                                                   v                             ",
   "                                                                                                                 ",
   "                                                                                                                ",
   "                                                                                                                 ",
   "                                                                                                                ",
   "                                                                                xx   xx                              ",
   "                                                                                xx   xx                              ",
   "    @                                                                           xx   xx                               ",
   "    xx                                          v                        xxxxx  xx   xx                                      ",
   "    xx                                                                          xx   xx                              ",
   "    xx                                                                          xx   xx                                ",
   "    xx      xxxxxx                                               xxxxxx         xx   xx                                           ",
   "    xx                                                                          xx   xx                               ",
   "    xx                  xxxxxx                           xxxx                   xx                                    ",
   "    xx                                                                          xx                                ",
   "x!!!xx!!!!!!!!!!!!!!!!!x                           xxx                          xx                                         ",
   "xxxxxxxxxxxxxxxxxxxxxxxx         x!!!xxxxxxxx!!!x                               xx             o                                     ",
   "                                 x!!!!!!!!!!!!!!x                               xxxxxxx    xxxxxx                                           ",
   "                                 xxxxxxxxxxxxxxxx                                                                                ",
   "                                                                                                                 ",
   "                                                                                                                 "],
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
